rclone:
  config_file: "D:\\kmati_ing\\kmati_ingestion\\extractor\\rclone.conf"

sources:
  - name: folder1
    remote: source
    bucket: mybucket/folder1

  - name: folder2
    remote: source
    bucket: mybucket/folder2

  - name: folder3
    remote: source
    bucket: mybucket/folder3

  - name: folder4
    remote: source
    bucket: mybucket/folder4

  - name: folder5
    remote: source
    bucket: mybucket/folder5

output:
  landing_zone: "target:target-bucket/landing"
  checkpoint_path: "D:\\kmati_ing\\kmati_ingestion\\extractor\\checkpoints\\minio_source.jsonl"
  metadata_path: "target:target-bucket/metadata"

settings: 
  mode: "full"        # full | incremental
  retries: 3
  retry_delay: 5
